// Generated by @foxgameowl/build. Do not edit — rebuild the title.
const CACHE = "fg-shengke-0.1.0";
const ASSETS = ["./","./assets/02-shanju-climb-BtsUr8qO.mp3","./assets/index-ZNS2rBed.css","./assets/index-rg0Ag9vJ.js"];

self.addEventListener('install', (event) => {
  // No skipWaiting: a new worker takes over on the next visit rather than
  // mid-session. Swapping code under a running game is how you get half the
  // old bundle talking to half the new one.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key.startsWith("fg-shengke-") && key !== CACHE)
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  // Someone else's host is someone else's business — and the analytics beacon
  // must never be answered from a cache of ours.
  if (url.origin !== self.location.origin) return;

  // Hashed assets can be trusted from the cache forever; everything else is
  // asked for first, so a release is picked up the moment the player is online
  // and only falls back to the cache when they are not.
  if (url.pathname.includes('/assets/')) {
    event.respondWith(caches.match(request).then((hit) => hit ?? fetch(request)));
    return;
  }

  event.respondWith(
    fetch(request)
      .then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      })
      .catch(() => caches.match(request).then((hit) => hit ?? caches.match('./'))),
  );
});
